attempt to use out_base instead of out_root for generated code
Error I'm getting for now:

$ bdep init
initializing in project E:\projects\megastructures\build2-godot-cpp\godot-cpp\
synchronizing:
  update godot-cpp/4.0.3
Assertion failed: r_->mode_ != members_mode::always, file E:\tools\build2\build2-toolchain-0.16-a.0\build2-0.16.0-a.0.20230529121200.0aa67f6106a0\libbuild2/target.ixx, line 588
error: process bpkg terminated abnormally: aborted